"use client";

import { useState } from "react";
import { Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, Check, ChevronRight, CircleCheck, Clock3, Database, LockKeyhole, Plug, RefreshCw, Sparkles, Store, X } from "lucide-react";

const providers = [
  { name: "Square", detail: "Square for Retail", mark: "S", color: "#20232a", tag: "POPULAR" },
  { name: "Shopify POS", detail: "Shopify point of sale", mark: "S", color: "#6b9d45", tag: "" },
  { name: "Lightspeed", detail: "Lightspeed Retail", mark: "L", color: "#5269a9", tag: "" },
  { name: "CSV import", detail: "Upload a sales export", mark: "↥", color: "#68778f", tag: "FLEXIBLE" },
];
const locations = [
  { name: "Northstar · Downtown", system: "Northstar Downtown", sales: "$24,860", match: "98.6%", skus: "1,284 / 1,302" },
  { name: "Northstar · Westside", system: "Northstar Westside", sales: "$17,820", match: "96.2%", skus: "1,252 / 1,301" },
];
const movers = [
  { name: "Sparkling Water · Lime", brand: "Spindrift", velocity: "22.6", change: "+14.2%", width: 92, color: "#7894d1" },
  { name: "Sea Salt Kettle Chips", brand: "Good & Gather", velocity: "18.4", change: "+8.7%", width: 76, color: "#d4a651" },
  { name: "Organic Oat Milk", brand: "Oatly", velocity: "19.1", change: "+6.1%", width: 67, color: "#7fa78c" },
];
const trend = [34, 47, 41, 58, 52, 71, 64, 82, 72, 88, 78, 96, 84, 100];

export default function SalesDataSetup({ companyName }: { companyName: string }) {
  const [provider, setProvider] = useState<string | null>(null);
  const [connectedProvider, setConnectedProvider] = useState("Sample POS feed");
  const [lastSync, setLastSync] = useState("Today, 9:14 AM");
  const [syncing, setSyncing] = useState(false);
  const [syncComplete, setSyncComplete] = useState(false);

  function syncDemo() {
    setSyncing(true); setSyncComplete(false);
    window.setTimeout(() => { setLastSync(`Today, ${new Date().toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}`); setSyncing(false); setSyncComplete(true); }, 900);
  }
  function finishConnection() { if (!provider) return; setConnectedProvider(provider); setLastSync("Just now"); setProvider(null); setSyncComplete(true); }

  return <div className="content sales-data-content">
    <div className="page-heading sales-data-heading"><div><div className="eyebrow">DATA CONNECTIONS · DEMO</div><h1>Sales data</h1><p>See how store-level POS data can power smarter shelf recommendations.</p></div><span className="sales-demo-badge"><span/> Mock setup · no live connection</span></div>
    <section className="sales-data-top-grid">
      <article className="card sales-connection-card"><div className="sales-card-kicker"><span className="sales-connected-icon"><Database size={15}/></span><span>ACTIVE DATA SOURCE</span><span className="sales-demo-pill">SAMPLE DATA</span></div><div className="sales-connection-title"><div><h2>{connectedProvider}</h2><p>{companyName} · POS sales and inventory</p></div><span className="sales-live-status"><i/>Demo connected</span></div><div className="sales-connection-stats"><div><small>LOCATIONS</small><strong>2</strong><span>stores syncing</span></div><div><small>SKU MATCH RATE</small><strong>97.4%</strong><span>product catalog matched</span></div><div><small>LAST SYNC</small><strong>{lastSync.startsWith("Today") ? lastSync.replace("Today, ", "") : lastSync}</strong><span>{lastSync.startsWith("Today") ? "Automatic refresh" : "Sample sync complete"}</span></div></div><div className="sales-connection-footer"><span><LockKeyhole size={12}/> Read-only access shown in this demo</span><button className="secondary-button" onClick={syncDemo} disabled={syncing}>{syncing ? <><RefreshCw size={13} className="sales-spinning"/> Syncing…</> : syncComplete ? <><Check size={13}/> Synced</> : <><RefreshCw size={13}/> Simulate sync</>}</button></div></article>
      <article className="card sales-impact-card"><div className="sales-impact-head"><div><span className="sales-impact-icon"><Sparkles size={15}/></span><span className="eyebrow">PLANOGRAM SIGNAL</span></div><span className="sales-confidence">READY TO OPTIMIZE</span></div><h2>Sales inform the next best facing</h2><p>Recent store-level demand helps rank products for available shelf space. Fixture dimensions stay as hard fit rules.</p><div className="sales-impact-equation"><span>28-day unit velocity</span><i>×</i><span>Margin & priority</span><ArrowRight size={13}/><strong>Facing recommendation</strong></div><div className="sales-impact-foot"><CircleCheck size={13}/> Example: use Downtown sales for its planograms</div></article>
    </section>

    <section className="sales-provider-section"><div className="sales-section-heading"><div><div className="eyebrow">INTEGRATIONS</div><h2>Connect a point-of-sale system</h2><p>Choose a provider to preview what a secure connection flow could look like.</p></div><span className="sales-mock-note"><LockKeyhole size={12}/> Demo only · no credentials collected</span></div><div className="sales-provider-grid">{providers.map(item => <article className="card sales-provider-card" key={item.name}><div className="sales-provider-top"><span className="sales-provider-mark" style={{ background: item.color }}>{item.mark}</span>{item.tag && <span className="sales-provider-tag">{item.tag}</span>}</div><h3>{item.name}</h3><p>{item.detail}</p><button className="sales-provider-button" onClick={() => setProvider(item.name)}><Plug size={12}/> Preview setup <ChevronRight size={12}/></button></article>)}</div></section>

    <section className="sales-overview-grid"><article className="card sales-trend-card"><div className="sales-overview-heading"><div><div className="eyebrow">SAMPLE PERFORMANCE</div><h2>Sales across your stores</h2><p>Daily net sales · last 14 days</p></div><button className="sales-period-select">Last 14 days <ChevronRight size={12}/></button></div><div className="sales-trend-summary"><strong>$42,680</strong><span><ArrowUpRight size={13}/> 8.4%</span><small>vs. previous period</small></div><div className="sales-bar-chart" role="img" aria-label="Sample daily sales for the past 14 days">{trend.map((value, index) => <div className="sales-bar-column" key={index}><span style={{ height: `${value}%` }}/>{index % 3 === 0 && <small>{index === 0 ? "Sep 20" : index === 6 ? "Sep 26" : index === 12 ? "Oct 2" : ""}</small>}</div>)}</div><div className="sales-chart-legend"><span><i/> Net sales</span><span>Sample data · USD</span></div></article>
      <article className="card sales-movers-card"><div className="sales-overview-heading"><div><div className="eyebrow">STORE-SPECIFIC DEMAND</div><h2>Top movers</h2><p>Downtown · units per day · 28-day average</p></div><button className="sales-location-select"><Store size={12}/> Downtown <ChevronRight size={12}/></button></div><div className="sales-movers-list">{movers.map((item, index) => <div className="sales-mover" key={item.name}><span className="sales-mover-rank">0{index + 1}</span><div className="sales-mover-copy"><strong>{item.name}</strong><small>{item.brand}</small><div className="sales-mover-track"><i style={{ width: `${item.width}%`, background: item.color }}/></div></div><div className="sales-mover-value"><strong>{item.velocity}</strong><small>units / day</small><span>{item.change}</span></div></div>)}</div><div className="sales-data-quality"><span><CircleCheck size={13}/> Catalog match</span><strong>97.4%</strong><div><i/></div><small>2,536 of 2,603 store SKUs matched</small></div></article></section>

    <section className="card sales-location-table"><div className="sales-section-heading"><div><div className="eyebrow">STORE MAPPING</div><h2>Sales data by location</h2><p>Each store’s sales are matched to its own product catalog.</p></div><button className="sales-export-button"><ArrowDownToLine size={13}/> Export mapping</button></div><div className="sales-table-scroll"><table><thead><tr><th>STORE LOCATION</th><th>POS LOCATION</th><th>14-DAY SALES</th><th>SKU MATCH</th><th>PRODUCTS</th><th>STATUS</th></tr></thead><tbody>{locations.map(item => <tr key={item.name}><td><div className="sales-table-location"><span><Store size={14}/></span><strong>{item.name}</strong></div></td><td>{item.system}</td><td><strong>{item.sales}</strong></td><td><span className="sales-match-pill">{item.match}</span></td><td>{item.skus}</td><td><span className="sales-row-status"><i/>Sample data</span></td></tr>)}</tbody></table></div><div className="sales-table-foot"><Activity size={12}/> Data refreshes on a schedule in this example. A live setup would show the provider’s actual sync time and connection health.</div></section>

    <div className="sales-ai-note"><span><Sparkles size={15}/></span><div><strong>How this supports AI-assisted merchandising</strong><p>Historical sales can estimate demand by store and SKU. The optimizer can use that signal to recommend facings while enforcing your shelf’s real width, height, and depth limits.</p></div><span className="sales-ai-note-tag">DEMO FLOW</span></div>

    {provider && <div className="modal-backdrop" onMouseDown={event => { if (event.target === event.currentTarget) setProvider(null); }}><div className="sales-connect-modal"><div className="product-modal-header"><div><div className="eyebrow">CONNECTION PREVIEW · STEP 1 OF 2</div><h2>{provider === "CSV import" ? "Set up a sales import" : `Connect ${provider}`}</h2><p>Preview the {provider === "CSV import" ? "file mapping" : "authorization"} experience for a company workspace.</p></div><button className="modal-close" onClick={() => setProvider(null)} aria-label="Close"><X size={17}/></button></div><div className="sales-connect-security"><span><LockKeyhole size={15}/></span><div><strong>{provider === "CSV import" ? "Map a sales export" : "Secure, read-only connection"}</strong><small>{provider === "CSV import" ? "In production, you would upload a POS export and map its store, SKU, date, and unit columns. This prototype does not upload or store a file." : `In production, you would authorize Shelfwise with ${provider}. This prototype does not request or store API keys.`}</small></div></div><div className="sales-connect-scopes"><strong>{provider === "CSV import" ? "Example columns to map" : "Example data access"}</strong><span><Check size={12}/> Store, SKU, date, units sold</span><span><Check size={12}/> Store locations and identifiers</span><span><Check size={12}/> Product catalog and SKU mapping</span><span><X size={12}/> No payment methods or customer details</span></div><div className="sales-connect-stores"><strong>Stores to include</strong><label><input type="checkbox" defaultChecked/> Northstar · Downtown <small>Store 018</small></label><label><input type="checkbox" defaultChecked/> Northstar · Westside <small>Store 024</small></label></div><div className="product-modal-footer"><span>Mock flow · no external service contacted</span><div><button className="secondary-button" onClick={() => setProvider(null)}>Cancel</button><button className="primary-button" onClick={finishConnection}><Check size={13}/> Simulate connection</button></div></div></div></div>}
  </div>;
}
